### ISSUE TITLE
Sprint 2: Refine Player UI

### ISSUE THREAD

**Issue by RZeng1999** [dalelion/DNDTools#18]
- [ ] #16 Create Initiative Tracker
- [ ] #19 Create a way to edit player's Stat Numbers
- [x] #20 Create in depth character screen
