### ISSUE TITLE
Sprint 1: Design UI

### ISSUE THREAD

**Issue by RZeng1999** [dalelion/DNDTools#2]
- [ ] #3 Create front page
- [ ] #4 Create room page
- [ ] #5 Create character page
- [x] #6 Create main page
