### ISSUE TITLE
Sprint 1: Coding

### ISSUE THREAD

**Issue by RZeng1999** [dalelion/DNDTools#7]
- [x] #8   - Connect Front Page to Main Page
- [x] #9   - Connect Main Page to Room Page
- [ ] #10 - Connect Room Page to Character Page
- [x] #11 - Update Main Page when in game
